// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Gridstack.Models;

public partial class GridstackContext : DbContext
{
    public GridstackContext()
    {
    }

    public GridstackContext(DbContextOptions<GridstackContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DetalleVentum> DetalleVenta { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<Venta> Ventas { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DetalleVentum>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DetalleV__3214EC075D781823");

            entity.Property(e => e.Subtotal).HasComputedColumnSql("([Cantidad]*[PrecioUnitario])", true);

            entity.HasOne(d => d.Producto).WithMany(p => p.DetalleVenta).HasConstraintName("FK__DetalleVe__Produ__403A8C7D");

            entity.HasOne(d => d.Venta).WithMany(p => p.DetalleVenta).HasConstraintName("FK__DetalleVe__Venta__3F466844");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Producto__3214EC076CB8F1BE");
        });

        modelBuilder.Entity<Venta>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ventas__3214EC0739B33FCF");

            entity.Property(e => e.Fecha).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}